### ISSUE TITLE
Tests don't currently pass

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-client-library#1]
There is an issue reading the included resources for the JSON and UriMap for the tests, so we get an error like this for all the tests:

```
java.lang.NullPointerException
    at org.onebusaway.io.client.mock.Resources.getTestUri(Resources.java:48)
    at org.onebusaway.io.client.mock.MockConnectionFactory.<init>(MockConnectionFactory.java:38)
    at org.onebusaway.io.client.mock.ObaMock.<init>(ObaMock.java:33)
    at org.onebusaway.io.client.test.ObaTestCase.setUp(ObaTestCase.java:37)
    at junit.framework.TestCase.runBare(TestCase.java:139)
    at junit.framework.TestResult$1.protect(TestResult.java:122)
    at junit.framework.TestResult.runProtected(TestResult.java:142)
    at junit.framework.TestResult.run(TestResult.java:125)
    at junit.framework.TestCase.run(TestCase.java:129)
    at junit.framework.TestSuite.runTest(TestSuite.java:252)
    at junit.framework.TestSuite.run(TestSuite.java:247)
    at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by barbeau** [comment]
Apparently it's impossible to get a Java `URI` to a resource in the `src/test/resources` folder - some related SO posts:
- http://stackoverflow.com/questions/16791439/android-how-to-get-uri-from-raw-file
- http://stackoverflow.com/questions/861500/url-to-load-resources-from-the-classpath-in-java

This is an issue because the OBA client is built around the concept of passing in URIs to define the base URL and path, and the tests previously used a URI to get the resources files on Android:
`private static final Uri TEST_RAW_URI =
            Uri.parse("android.resource://com.joulespersecond.seattlebusbot.test/raw/");`

The bundled test files are sample JSON responses from the various APIs, used to exercise the code.

So, our options are to rewrite the library away from URIs, or some up with another way to execute the tests that aren't dependent on URIs to bundled resource files.

One option is to use URIs to the same files hosted publicly in this repo on Github - for example:
https://raw.githubusercontent.com/OneBusAway/onebusaway-client-library/master/src/test/resources/agencies_with_coverage.json

This would require a machine to have an internet connection to run the tests.
