### ISSUE TITLE
Clock time unit test fails on Travis (but passes on my machine)

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-client-library#19]
We now have clock times for arrivals/depatures supported as well as ETAs, via https://github.com/OneBusAway/onebusaway-client-library/issues/16.

The new unit test for clock times (`UIUtilTest.testArrivalSummaryClockTime()`)passes on my machine, but fails on Travis.  From a quick look I believe this is a time zone issue, as it appears that the expected clock times in the unit tests are "3:51 PM" but the actual times on Travis as "7:51 PM".

Failing build on Travis:
https://travis-ci.org/OneBusAway/onebusaway-client-library/builds/200792673

Output:

~~~
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.081 sec <<< FAILURE!
testArrivalSummaryClockTime(org.onebusaway.io.client.test.UIUtilTest)  Time elapsed: 0.046 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<... 15th St arrived at [3:51 PM and is arriving again at 4:30 PM
Route 6 South to Downtown/MTC departed at 3:52 PM and is departing again at 4:09 PM and 4:30 PM
Route 1 UATC to Downtown via Florida Ave departed at 3:54 PM and is departing again at 4:20 PM
Route 18 North to UATC/Livingston arrived at 3:54 PM and is arriving again at 4:23 PM and 4:27 PM
Route 5 South to Downtown/MTC departed at 3:54 PM and is departing again at 4:30 PM
Route 2 UATC to Downtown via Nebraska Ave is departing now and again at 4:25 PM
Route 18 South to UATC/Downtown/MTC is arriving now and again at 4:05 PM and 4:25 PM
Route 12 North to University Area TC is arriving at 3:58 PM and 4:21 PM
Route 9 UATC to Downtown via 15th St is departing at 4:00 PM, 4:30 PM, 5:20 PM, and 5:25 PM
Route 12 South to Downtown/MTC is departing at 4:00 PM and 4:22 PM
Route 5 North to University Area TC is arriving at 4:01 PM and 4:27 PM
Route 6 North to University Area TC is arriving at 4:02 PM and 4:29 PM
Route 1 Downtown to UATC via Florida Ave is arriving at 4:12 PM and 4:29 PM
Route 45 North to University Area TC is arriving at 4:15 PM
Route 45 South to Westshore TC is departing at 4:15 PM
Route 2 Downtown to UATC via Nebraska Ave is arriving at 4:18 PM
Route 9 UATC to Downtown via 15th St is departing at 5]:43 PM based on the ...> but was:<... 15th St arrived at [7:51 PM and is arriving again at 8:30 PM
Route 6 South to Downtown/MTC departed at 7:52 PM and is departing again at 8:09 PM and 8:30 PM
Route 1 UATC to Downtown via Florida Ave departed at 7:54 PM and is departing again at 8:20 PM
Route 18 North to UATC/Livingston arrived at 7:54 PM and is arriving again at 8:23 PM and 8:27 PM
Route 5 South to Downtown/MTC departed at 7:54 PM and is departing again at 8:30 PM
Route 2 UATC to Downtown via Nebraska Ave is departing now and again at 8:25 PM
Route 18 South to UATC/Downtown/MTC is arriving now and again at 8:05 PM and 8:25 PM
Route 12 North to University Area TC is arriving at 7:58 PM and 8:21 PM
Route 9 UATC to Downtown via 15th St is departing at 8:00 PM, 8:30 PM, 9:20 PM, and 9:25 PM
Route 12 South to Downtown/MTC is departing at 8:00 PM and 8:22 PM
Route 5 North to University Area TC is arriving at 8:01 PM and 8:27 PM
Route 6 North to University Area TC is arriving at 8:02 PM and 8:29 PM
Route 1 Downtown to UATC via Florida Ave is arriving at 8:12 PM and 8:29 PM
Route 45 North to University Area TC is arriving at 8:15 PM
Route 45 South to Westshore TC is departing at 8:15 PM
Route 2 Downtown to UATC via Nebraska Ave is arriving at 8:18 PM
Route 9 UATC to Downtown via 15th St is departing at 9]:43 PM based on the ...>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at junit.framework.TestCase.assertEquals(TestCase.java:269)
	at org.onebusaway.io.client.test.UIUtilTest.testArrivalSummaryClockTime(UIUtilTest.java:315)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
~~~

**Comment by barbeau** [comment]
Thinking more, we'll need to allow app to pass in timezone info. For OBA Alexa, this code will be running on an Eastern Lambda instance, so we can't assume code is running in the same timezone as the device that will be giving the user arrival times.
